### ISSUE TITLE
Verify #9 block-level CSS actually applies in real Calibre conversions (Stylizer opts silent-failure found in #15)

### ISSUE THREAD

**Issue by jloutsch** [jloutsch/kfxgen#33]
## Summary

While verifying #15 with a real `ebook-convert` run, the conversion log showed:

```
Stylizer unavailable ('OEBBook' object has no attribute 'opts'); skipping per-element CSS
```

The per-element style resolver (`converter.py::_build_style_resolver`) reads
`oeb_book.opts` to construct a Calibre `Stylizer`. In Calibre's output-plugin
pipeline (`OutputFormatPlugin.convert(oeb_book, output_path, input_plugin, opts, log)`)
the `opts` are passed as a **separate argument** and the `OEBBook` has no `.opts`
attribute (observed on Calibre 9.8). So Stylizer construction raised, the resolver
returned `None`, and **every block got `block_style = None`** — meaning block-level
CSS (`text-align`, `text-indent`, `margin-left/right`, and, as of #15,
`font-family`) was silently dropped and paragraphs fell back to generator defaults.

This was fixed for the font path as part of #15 (commit adding `_ensure_oeb_opts`,
which attaches the conversion `opts` to `oeb_book` so both the #9 resolver and #15
font extraction can build a Stylizer). After the fix, the real conversion emits the
CSS-derived styles and embeds fonts.

## Why a follow-on issue

The `_ensure_oeb_opts` fix repairs the path, but it raises a question the #15 work
did not fully answer: **was the #9 block-styling (CSS typography — alignment,
indent, margins) ever actually verified against a real Calibre conversion, or did
those checks pass on the Calibre-free test shim / native path where the Stylizer is
never constructed?**

The unit/integration tests use `EpubAsOeb` (a Calibre-free shim) or inject a fake
style resolver, so they never exercise real `Stylizer` construction — which is
exactly why this silent failure went unnoticed. See the note in memory:
"Calibre Stylizer signature: Stylizer(tree, path, oeb, opts, profile); only
exercised by a real conversion, not the test shim."

## What to check

- [ ] Confirm block CSS (alignment / indent / margins) now actually renders from a
      **real** `ebook-convert` run on a book that uses those CSS properties — not
      just the shim tests. Compare a real KFX's `$157` styles before/after
      `_ensure_oeb_opts`.
- [ ] Decide whether the earlier #9 device-verification (if any) needs re-running,
      since it may have validated generator defaults rather than source CSS.
- [ ] Add a regression test that exercises the real `Stylizer` path (Calibre-gated,
      `@pytest.mark.integration`), so a future `oeb_book.opts` / Stylizer-signature
      regression fails a test instead of silently degrading. The current shim-based
      tests cannot catch this class of bug.
- [ ] Audit for any other `oeb_book.opts` / Stylizer assumptions that only run under
      real Calibre and are unguarded by tests.

## Context

- Discovered during #15 (native font embedding) real-conversion verification.
- Root-cause fix: `_ensure_oeb_opts` on branch `feat/15-native-font-embed`.
- Related: #9 (inline emphasis + CSS typography), #18 (kfxlib/Calibre drift tracking).
